function initializeLevel (level: number) {
    effects.clouds.startScreenEffect()
    playerStartLocation = tiles.getTilesByType(assets.tile`tile6`)[0]
    tiles.placeOnTile(hero, playerStartLocation)
    tiles.setTileAt(playerStartLocation, assets.tile`tile6`)
    function createEnemies (){
        for (let bLoc of tiles.getTilesByType(assets.tile` tile4`)){
            
        }
        for (let bumperLocation of tiles.getTilesByType(assets.tile`tile7 `)){
            bumper = sprites.create(img`
                ................................
                ................................
                ................................
                ................................
                ................................
                ............ffff................
                ..........ffeeeeff..............
                .........ffffeeffff.............
                ..........f1feef1f..............
                .........fe11ff11ef.............
                .......ffee1feef1eeff...........
                ......feeee1feef1eeeef..........
                ......feeeeeeeeeeeeeef..........
                .......fee1ffffff1eef...........
                ........fe1eeeeee1ef............
                .........ffffffffff.............
                ..........fddddddf..............
                ........feeddddddeef............
                ......feeeeddddddeeeef..........
                .....feeeeeeddddeeeeeef.........
                ....feeeeeeeffffeeeeeeef........
                ...feeeeeeeef..feeeeeeeef.......
                ....ffffffff.....fffffff........
                ................................
                ................................
                ................................
                ................................
                ................................
                ................................
                ................................
                ................................
                ................................
            `, SpriteKind.Bumper)
            tiles.placeOnTile(bumper, bumperLocation)
            tiles.setTileAt(bumperLocation, assets.tile`tile0`)
            bumper.ay = gravity
            if (Math.percentChance(50)){
                bumper.vx = randint(30, 60)
            }
            else{
                bumper.vx = randint (-60, -30)
            }
        }
        for (let flierLocation of tiles.getTilesByType(assets.tile` tile7`)){
          flier =  sprites.create(flierImgs[0], SpriteKind.Flier)
          tiles.placeOnTile(flier, flierLocation) 
          tiles.setTileAt(flierLocation, assets.tile` tile0`) 
        }
    }
}

initializeLevel(currentLevel)
